//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballMates
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FootballMatesEntities : DbContext
    {
        public FootballMatesEntities()
            : base("name=FootballMatesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblClub> TblClubs { get; set; }
        public virtual DbSet<TblManager> TblManagers { get; set; }
        public virtual DbSet<TblPlayer> TblPlayers { get; set; }
        public virtual DbSet<TblPosition> TblPositions { get; set; }
    
        public virtual int sProc_Club_Delete(Nullable<int> clubId)
        {
            var clubIdParameter = clubId.HasValue ?
                new ObjectParameter("ClubId", clubId) :
                new ObjectParameter("ClubId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sProc_Club_Delete", clubIdParameter);
        }
    
        public virtual ObjectResult<sProc_Club_Read_Result> sProc_Club_Read(Nullable<int> clubId)
        {
            var clubIdParameter = clubId.HasValue ?
                new ObjectParameter("ClubId", clubId) :
                new ObjectParameter("ClubId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sProc_Club_Read_Result>("sProc_Club_Read", clubIdParameter);
        }
    
        public virtual ObjectResult<sProc_Club_ReadEverything_Result> sProc_Club_ReadEverything()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sProc_Club_ReadEverything_Result>("sProc_Club_ReadEverything");
        }
    
        public virtual ObjectResult<Nullable<decimal>> sProc_Club_Write(Nullable<int> clubId, string clubName, string country, string stadium, Nullable<int> yearFounded, byte[] clubLogo)
        {
            var clubIdParameter = clubId.HasValue ?
                new ObjectParameter("ClubId", clubId) :
                new ObjectParameter("ClubId", typeof(int));
    
            var clubNameParameter = clubName != null ?
                new ObjectParameter("ClubName", clubName) :
                new ObjectParameter("ClubName", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var stadiumParameter = stadium != null ?
                new ObjectParameter("Stadium", stadium) :
                new ObjectParameter("Stadium", typeof(string));
    
            var yearFoundedParameter = yearFounded.HasValue ?
                new ObjectParameter("YearFounded", yearFounded) :
                new ObjectParameter("YearFounded", typeof(int));
    
            var clubLogoParameter = clubLogo != null ?
                new ObjectParameter("ClubLogo", clubLogo) :
                new ObjectParameter("ClubLogo", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sProc_Club_Write", clubIdParameter, clubNameParameter, countryParameter, stadiumParameter, yearFoundedParameter, clubLogoParameter);
        }
    }
}
