//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballMates
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblClub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblClub()
        {
            this.TblManagers = new HashSet<TblManager>();
            this.TblPlayers = new HashSet<TblPlayer>();
        }
    
        public int ClubId { get; set; }
        public string ClubName { get; set; }
        public string Country { get; set; }
        public string Stadium { get; set; }
        public Nullable<int> YearFounded { get; set; }
        public byte[] ClubLogo { get; set; }
        public string ClubDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblManager> TblManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPlayer> TblPlayers { get; set; }
    }
}
